import { Card, CardContent } from "@/components/ui/card";
import MineSweeperImagePng from "../assets/Minesweeper.png";
import MineSweeperImageWebp from "../assets/Minesweeper.webp";
import RummyImagePng from "../assets/rummy.png";
import RummyImageWebp from "../assets/rummy.webp";
import SevenUpandSevenDownImagePng from "../assets/7_Up_7_Down.png";
import SevenUpandSevenDownImageWebp from "../assets/7_Up_7_Down.webp";
import DragonTigerImagePng from "../assets/Dragon_Tiger.png";
import DragonTigerImageWebp from "../assets/Dragon_Tiger.webp";
import MegaFishingImagePng from "../assets/megaFishing.png";
import MegaFishingImageWebp from "../assets/megaFishing.webp";
import RouletteImagePng from "../assets/European_Roulette.png";
import RouletteImageWebp from "../assets/European_Roulette.webp";
import CoinTossImagePng from "../assets/Coin_Toss.png";
import CoinTossImageWebp from "../assets/Coin_Toss.webp";
import TeenPattiImagePng from "../assets/teenPatti.png";
import TeenPattiImageWebp from "../assets/teenPatti.webp";

import TeenPattiLiveImagePng from "../assets/liveteenpatti.png";
import TeenPattiLiveImageWebp from "../assets/liveteenpatti.webp";
import AndarBaharImagePng from "../assets/andarbahar.png";
import AndarBaharImageWebp from "../assets/andarbahar.webp";
import Roulette1ImagePng from "../assets/roullete.png";
import Roulette1ImageWebp from "../assets/roullete.webp";
import CasinoWarImagePng from "../assets/casinowar.png";
import CasinoWarImageWebp from "../assets/casinowar.webp";
import HiLowImagePng from "../assets/hi-low.png";
import HiLowImageWebp from "../assets/hi-low.webp";
import TwoCardsTeenpattiImagePng from "../assets/2cards_teenpatti.png";
import TwoCardsTeenpattiImageWebp from "../assets/2cards_teenpatti.webp";
import TeenpattiT20ImagePng from "../assets/teenpattit20.png";
import TeenpattiT20ImageWebp from "../assets/teenpattit20.webp";
import AmarAkbarAnthonyImagePng from "../assets/aaa.png";
import AmarAkbarAnthonyImageWebp from "../assets/aaa.webp";
import CardsCasinoImagePng from "../assets/32casino.png";
import CardsCasinoImageWebp from "../assets/32casino.webp";
import TeenpattiTestImagePng from "../assets/teenpatti_test.png";
import TeenpattiTestImageWebp from "../assets/teenpatti_test.webp";
import PokerImagePng from "../assets/2020poker.png";
import PokerImageWebp from "../assets/2020poker.webp";
import MuflisTeenpattiImagePng from "../assets/Muflis_teenpatti.png";
import MuflisTeenpattiImageWebp from "../assets/Muflis_teenpatti.webp";
// Responsive srcset imports generated by vite-imagetools
import SevenUpandSevenDownImageWebpSet from "../assets/7_Up_7_Down.png?w=200;320;480;640;800&format=webp&as=srcset";
import SevenUpandSevenDownImagePngSet from "../assets/7_Up_7_Down.png?w=200;320;480;640;800&format=png&as=srcset";
import DragonTigerImageWebpSet from "../assets/Dragon_Tiger.png?w=200;320;480;640;800&format=webp&as=srcset";
import DragonTigerImagePngSet from "../assets/Dragon_Tiger.png?w=200;320;480;640;800&format=png&as=srcset";
import RouletteImageWebpSet from "../assets/European_Roulette.png?w=200;320;480;640;800&format=webp&as=srcset";
import RouletteImagePngSet from "../assets/European_Roulette.png?w=200;320;480;640;800&format=png&as=srcset";
import MineSweeperImageWebpSet from "../assets/Minesweeper.png?w=200;320;480;640;800&format=webp&as=srcset";
import MineSweeperImagePngSet from "../assets/Minesweeper.png?w=200;320;480;640;800&format=png&as=srcset";
import RummyImageWebpSet from "../assets/rummy.png?w=200;320;480;640;800&format=webp&as=srcset";
import RummyImagePngSet from "../assets/rummy.png?w=200;320;480;640;800&format=png&as=srcset";
import MegaFishingImageWebpSet from "../assets/megaFishing.png?w=200;320;480;640;800&format=webp&as=srcset";
import MegaFishingImagePngSet from "../assets/megaFishing.png?w=200;320;480;640;800&format=png&as=srcset";
import TeenPattiImageWebpSet from "../assets/teenPatti.png?w=200;320;480;640;800&format=webp&as=srcset";
import TeenPattiImagePngSet from "../assets/teenPatti.png?w=200;320;480;640;800&format=png&as=srcset";
import CoinTossImageWebpSet from "../assets/Coin_Toss.png?w=200;320;480;640;800&format=webp&as=srcset";
import CoinTossImagePngSet from "../assets/Coin_Toss.png?w=200;320;480;640;800&format=png&as=srcset";

import TeenPattiLiveImageWebpSet from "../assets/liveteenpatti.png?w=200;320;480;640;800&format=webp&as=srcset";
import TeenPattiLiveImagePngSet from "../assets/liveteenpatti.png?w=200;320;480;640;800&format=png&as=srcset";
import AndarBaharImageWebpSet from "../assets/andarbahar.png?w=200;320;480;640;800&format=webp&as=srcset";
import AndarBaharImagePngSet from "../assets/andarbahar.png?w=200;320;480;640;800&format=png&as=srcset";
import Roulette1ImageWebpSet from "../assets/roullete.png?w=200;320;480;640;800&format=webp&as=srcset";
import Roulette1ImagePngSet from "../assets/roullete.png?w=200;320;480;640;800&format=png&as=srcset";
import CasinoWarImageWebpSet from "../assets/casinowar.png?w=200;320;480;640;800&format=webp&as=srcset";
import CasinoWarImagePngSet from "../assets/casinowar.png?w=200;320;480;640;800&format=png&as=srcset";
import HiLowImageWebpSet from "../assets/hi-low.png?w=200;320;480;640;800&format=webp&as=srcset";
import HiLowImagePngSet from "../assets/hi-low.png?w=200;320;480;640;800&format=png&as=srcset";
import TwoCardsTeenpattiImageWebpSet from "../assets/2cards_teenpatti.png?w=200;320;480;640;800&format=webp&as=srcset";
import TwoCardsTeenpattiImagePngSet from "../assets/2cards_teenpatti.png?w=200;320;480;640;800&format=png&as=srcset";
import TeenpattiT20ImageWebpSet from "../assets/teenpattit20.png?w=200;320;480;640;800&format=webp&as=srcset";
import TeenpattiT20ImagePngSet from "../assets/teenpattit20.png?w=200;320;480;640;800&format=png&as=srcset";
import AmarAkbarAnthonyImageWebpSet from "../assets/aaa.png?w=200;320;480;640;800&format=webp&as=srcset";
import AmarAkbarAnthonyImagePngSet from "../assets/aaa.png?w=200;320;480;640;800&format=png&as=srcset";
import CardsCasinoImageWebpSet from "../assets/32casino.png?w=200;320;480;640;800&format=webp&as=srcset";
import CardsCasinoImagePngSet from "../assets/32casino.png?w=200;320;480;640;800&format=png&as=srcset";
import TeenpattiTestImageWebpSet from "../assets/teenpatti_test.png?w=200;320;480;640;800&format=webp&as=srcset";
import TeenpattiTestImagePngSet from "../assets/teenpatti_test.png?w=200;320;480;640;800&format=png&as=srcset";
import PokerImageWebpSet from "../assets/2020poker.png?w=200;320;480;640;800&format=webp&as=srcset";
import PokerImagePngSet from "../assets/2020poker.png?w=200;320;480;640;800&format=png&as=srcset";
import MuflisTeenpattiImageWebpSet from "../assets/Muflis_teenpatti.png?w=200;320;480;640;800&format=webp&as=srcset";
import MuflisTeenpattiImagePngSet from "../assets/Muflis_teenpatti.png?w=200;320;480;640;800&format=png&as=srcset";


const casinoGames = [
  { name: "7 up and 7 down", iconPng: SevenUpandSevenDownImagePng, iconWebp: SevenUpandSevenDownImageWebp, webpSet: SevenUpandSevenDownImageWebpSet, pngSet: SevenUpandSevenDownImagePngSet },
  { name: "Dragon Tiger", iconPng: DragonTigerImagePng, iconWebp: DragonTigerImageWebp, webpSet: DragonTigerImageWebpSet, pngSet: DragonTigerImagePngSet },
  { name: "Roulette", iconPng: RouletteImagePng, iconWebp: RouletteImageWebp, webpSet: RouletteImageWebpSet, pngSet: RouletteImagePngSet },
  { name: "Mine Sweeper", iconPng: MineSweeperImagePng, iconWebp: MineSweeperImageWebp, webpSet: MineSweeperImageWebpSet, pngSet: MineSweeperImagePngSet },
  { name: "Rummy", iconPng: RummyImagePng, iconWebp: RummyImageWebp, webpSet: RummyImageWebpSet, pngSet: RummyImagePngSet },
  { name: "Mega Fishing", iconPng: MegaFishingImagePng, iconWebp: MegaFishingImageWebp, webpSet: MegaFishingImageWebpSet, pngSet: MegaFishingImagePngSet },
  { name: "Teen Patti", iconPng: TeenPattiImagePng, iconWebp: TeenPattiImageWebp, webpSet: TeenPattiImageWebpSet, pngSet: TeenPattiImagePngSet },
  { name: "Coin Toss", iconPng: CoinTossImagePng, iconWebp: CoinTossImageWebp, webpSet: CoinTossImageWebpSet, pngSet: CoinTossImagePngSet },
];

const indianCardGames = [
  { name: "Teenpatti", iconPng: TeenPattiLiveImagePng, iconWebp: TeenPattiLiveImageWebp, webpSet: TeenPattiLiveImageWebpSet, pngSet: TeenPattiLiveImagePngSet },
  { name: "Andar Bahar", iconPng: AndarBaharImagePng, iconWebp: AndarBaharImageWebp, webpSet: AndarBaharImageWebpSet, pngSet: AndarBaharImagePngSet },
  { name: "Roulette", iconPng: Roulette1ImagePng, iconWebp: Roulette1ImageWebp, webpSet: Roulette1ImageWebpSet, pngSet: Roulette1ImagePngSet },
  { name: "Casino War", iconPng: CasinoWarImagePng, iconWebp: CasinoWarImageWebp, webpSet: CasinoWarImageWebpSet, pngSet: CasinoWarImagePngSet },
  { name: "Hi Low", iconPng: HiLowImagePng, iconWebp: HiLowImageWebp, webpSet: HiLowImageWebpSet, pngSet: HiLowImagePngSet },
  { name: "2 Cards Teenpatti", iconPng: TwoCardsTeenpattiImagePng, iconWebp: TwoCardsTeenpattiImageWebp, webpSet: TwoCardsTeenpattiImageWebpSet, pngSet: TwoCardsTeenpattiImagePngSet },
  { name: "Teenpatti T20", iconPng: TeenpattiT20ImagePng, iconWebp: TeenpattiT20ImageWebp, webpSet: TeenpattiT20ImageWebpSet, pngSet: TeenpattiT20ImagePngSet },
  { name: "Amar Akbar Anthony", iconPng: AmarAkbarAnthonyImagePng, iconWebp: AmarAkbarAnthonyImageWebp, webpSet: AmarAkbarAnthonyImageWebpSet, pngSet: AmarAkbarAnthonyImagePngSet },
  { name: "32 Cards Casino", iconPng: CardsCasinoImagePng, iconWebp: CardsCasinoImageWebp, webpSet: CardsCasinoImageWebpSet, pngSet: CardsCasinoImagePngSet },
  { name: "Teenpatti Test", iconPng: TeenpattiTestImagePng, iconWebp: TeenpattiTestImageWebp, webpSet: TeenpattiTestImageWebpSet, pngSet: TeenpattiTestImagePngSet },
  { name: "20 20 Poker", iconPng: PokerImagePng, iconWebp: PokerImageWebp, webpSet: PokerImageWebpSet, pngSet: PokerImagePngSet },
  { name: "Muflis Teenpatti", iconPng: MuflisTeenpattiImagePng, iconWebp: MuflisTeenpattiImageWebp, webpSet: MuflisTeenpattiImageWebpSet, pngSet: MuflisTeenpattiImagePngSet },
];

export const CasinoSection = () => {
  const openWhatsApp = () => {
    const phoneNumber = "918890051287";
    const message = "Hi, I want to login to Reddy Anna Live!";
    window.open(
      `https://api.whatsapp.com/send?phone=${phoneNumber}&text=${encodeURIComponent(
        message,
      )}`,
      "_blank",
    );
  };

  return (
    <section id="casino" className="py-12 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4">
        {/* Section Title */}
        <div className="w-full mb-12">
          <div className="text-center">
            <h2 className="text-3xl font-bold w-full py-4 px-8 rounded-lg bg-gradient-to-r from-yellow-400 to-orange-500 text-white shadow-lg transition-all duration-300 hover:shadow-xl mb-4">
              Live Casino Games
            </h2>
            <p className="text-gray-600 text-lg max-w-3xl mx-auto">
              Experience the thrill of live casino games with Reddy Anna Live. Play popular casino games like roulette, 
              poker, teen patti, andar bahar, and more with live dealers and real-time gameplay.
            </p>
          </div>
        </div>

        {/* Casino Games */}
       <div className="mb-12 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 justify-items-center">
  {casinoGames.map((game, index) => (
    <Card
      key={index}
      className="hover:shadow-xl hover:scale-105 transition-transform duration-300 ease-out cursor-pointer overflow-hidden inline-block"
      onClick={openWhatsApp}
    >
      <CardContent className="p-0 flex items-center justify-center bg-black">
        <picture>
          <source srcSet={game.webpSet} type="image/webp" />
          <source srcSet={game.pngSet} type="image/png" />
          <img
            src={game.iconPng}
            alt={game.name}
            loading="lazy"
            decoding="async"
            className="object-contain"
            sizes="(min-width: 1024px) 200px, (min-width: 768px) 240px, (min-width: 640px) 280px, 320px"
          />
        </picture>
      </CardContent>
      <div className="text-center py-2">
        <h4 className="text-lg font-semibold">{game.name}</h4>
      </div>
    </Card>
  ))}
</div>



        {/* Indian Card Games Title */}
        <h2 className="text-3xl font-bold mb-12 text-center w-full py-4 px-8 rounded-lg bg-gradient-to-r from-yellow-400 to-orange-500 text-white shadow-lg transition-all duration-300 hover:shadow-xl">
          Indian Card Games
        </h2>

        {/* Indian Card Games */}
        <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-8">
          {indianCardGames.map((game, index) => (
            <Card
              key={index}
              className="hover:shadow-xl hover:scale-105 transition-transform duration-300 ease-out cursor-pointer overflow-hidden inline-block"
              onClick={openWhatsApp}
            >
              <CardContent className="p-0 flex items-center justify-center bg-black">
                <picture>
                  <source srcSet={game.webpSet} type="image/webp" />
                  <source srcSet={game.pngSet} type="image/png" />
                  <img
                    src={game.iconPng}
                    alt={game.name}
                    loading="lazy"
                    decoding="async"
                    className="object-contain"
                    sizes="(min-width: 1024px) 200px, (min-width: 768px) 240px, (min-width: 640px) 280px, 320px"
                  />
                </picture>
              </CardContent>
              <div className="text-center py-2">
                <h4 className="text-lg font-semibold">{game.name}</h4>
              </div>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
};
